# Generated by Django 2.1 on 2018-09-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('file', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('num', models.CharField(max_length=12)),
                ('fecha', models.DateField()),
                ('fecha_cancelado', models.DateField(default=None)),
                ('pagada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rut',
            fields=[
                ('digits', models.BigIntegerField(primary_key=True, serialize=False)),
                ('verify', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('rut', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='FacturaDB.Rut')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FacturaDB.Client'),
        ),
    ]
